/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#263da0",
        "primary-fixed": "#dee1ff",
        "on-surface": "#0b1c30",
        "secondary-fixed": "#9cf0ff",
        "on-secondary-fixed": "#001f24",
        "inverse-surface": "#213145",
        "surface-variant": "#d3e4fe",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface": "#f8f9ff",
        "secondary-fixed-dim": "#00daf3",
        "primary-fixed-dim": "#b9c3ff",
        "on-surface-variant": "#454652",
        "outline": "#757684",
        "outline-variant": "#c5c5d4",
        "on-tertiary-container": "#b7b8ff",
        "surface-container-highest": "#d3e4fe",
        "error-container": "#ffdad6",
        "primary-container": "#2e44a7",
        "on-error-container": "#93000a",
        "on-primary-container": "#afbbff",
        "on-secondary-container": "#00616d",
        "inverse-on-surface": "#eaf1ff",
        "surface-bright": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#0b1c30",
        "tertiary-fixed": "#e1e0ff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#4156b9",
        "tertiary": "#1a12af",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed-variant": "#004f58",
        "primary": "#0f2a90",
        "surface-container-high": "#dce9ff",
        "surface-container": "#e5eeff",
        "on-error": "#ffffff",
        "secondary-container": "#00e3fd",
        "on-primary-fixed": "#001258",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "background": "#f8f9ff",
        "secondary": "#006875",
        "inverse-primary": "#b9c3ff",
        "tertiary-container": "#3636c5",
        "on-tertiary-fixed": "#07006c"
      },
      borderRadius: {
        "sm": "6px",
        "DEFAULT": "8px",
        "md": "10px",
        "lg": "12px",
        "xl": "16px",
        "2xl": "20px",
        "3xl": "24px",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "container-max": "1280px",
        "sm": "8px",
        "xs": "4px",
        "lg": "24px",
        "gutter": "20px",
        "base": "4px",
        "xl": "40px"
      },
      fontFamily: {
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "headline-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["13px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-lg-mobile": ["26px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
